CREATE TABLE FABRICANT (
	COD_FABRICANT NUMERIC(3),
	NOM VARCHAR(15),
    PAIS VARCHAR(15),
	CONSTRAINT PK_FABRICANT PRIMARY KEY (COD_FABRICANT),
    CONSTRAINT CK_NOM CHECK (NOM = UPPER(NOM)),
    CONSTRAINT CK_PAIS CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE ARTICLE (
	COD_ARTICLE VARCHAR(20),
	COD_FABRICANT NUMERIC(3),
    PES NUMERIC(3),
    CATEGORIA VARCHAR(10),
    PREU_VENDA DECIMAL(6,2),
    PREU_COST DECIMAL(6,2),
    STOCK NUMERIC(5),
	CONSTRAINT PK_PRODUCTE PRIMARY KEY (COD_ARTICLE, COD_FABRICANT, PES, CATEGORIA),
    CONSTRAINT FK_FABRICANT FOREIGN KEY (COD_FABRICANT) REFERENCES FABRICANT(COD_FABRICANT),
    CONSTRAINT CK_PREUVENDA CHECK (PREU_VENDA > 0),
    CONSTRAINT CK_PREUCOST CHECK (PREU_COST > 0 ),
    CONSTRAINT CK_PES CHECK (PES > 0),
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN ('Primera', 'Segona', 'Tercera'))
);